import React, { useState } from 'react';
import {
  Globe,
  GitBranch,
  Cloud,
  CheckCircle2,
  Copy,
  X,
  Server,
  Layers,
} from 'lucide-react';

interface DeploymentGuideModalProps {
  onClose: () => void;
  onNotification: (msg: string, type?: 'success' | 'error' | 'info') => void;
}

export const DeploymentGuideModal: React.FC<DeploymentGuideModalProps> = ({
  onClose,
  onNotification,
}) => {
  const [activePlatform, setActivePlatform] = useState<'cloudflare' | 'github' | 'cloudrun'>('cloudflare');
  const [copiedCmd, setCopiedCmd] = useState<string | null>(null);

  const copyToClipboard = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedCmd(id);
    onNotification('Code command copied to clipboard!', 'success');
    setTimeout(() => setCopiedCmd(null), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/75 p-4 backdrop-blur-xs">
      <div className="bg-white rounded-2xl shadow-2xl max-w-3xl w-full border border-slate-200 overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in-95 duration-150">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-5 border-b border-slate-200 bg-slate-50/80">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-blue-600 text-white">
              <Globe className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-bold text-slate-900">
                Nexus Academy — Global Deployment &amp; Publishing Guide
              </h3>
              <p className="text-xs text-slate-500">
                Production architecture breakdown for Cloudflare Pages, GitHub, or Cloud Run.
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-slate-400 hover:text-slate-600 transition cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Tab Selectors */}
        <div className="grid grid-cols-3 bg-slate-100 border-b border-slate-200 p-1.5 text-xs font-bold text-center">
          <button
            onClick={() => setActivePlatform('cloudflare')}
            className={`py-2 px-3 rounded-lg flex items-center justify-center gap-1.5 transition cursor-pointer ${
              activePlatform === 'cloudflare'
                ? 'bg-white text-orange-600 shadow-xs'
                : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            <Cloud className="w-4 h-4" /> Cloudflare Pages / Workers
          </button>

          <button
            onClick={() => setActivePlatform('github')}
            className={`py-2 px-3 rounded-lg flex items-center justify-center gap-1.5 transition cursor-pointer ${
              activePlatform === 'github'
                ? 'bg-white text-slate-900 shadow-xs'
                : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            <GitBranch className="w-4 h-4" /> GitHub Repository / Pages
          </button>

          <button
            onClick={() => setActivePlatform('cloudrun')}
            className={`py-2 px-3 rounded-lg flex items-center justify-center gap-1.5 transition cursor-pointer ${
              activePlatform === 'cloudrun'
                ? 'bg-white text-blue-600 shadow-xs'
                : 'text-slate-600 hover:text-slate-900'
            }`}
          >
            <Server className="w-4 h-4" /> Cloud Run &amp; Port 3000
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto space-y-5 text-xs text-slate-700">
          {activePlatform === 'cloudflare' && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-orange-50/70 border border-orange-200 text-orange-900 leading-relaxed">
                <strong>Deploying to Cloudflare Pages:</strong> Cloudflare provides high speed global CDN edges, custom domains with free SSL, and zero cold starts.
              </div>

              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-2 flex items-center gap-1.5">
                  <Layers className="w-4 h-4 text-orange-600" /> Separated File Parts for Cloudflare:
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 font-mono text-[11px]">
                  <div className="p-2.5 bg-slate-50 border border-slate-200 rounded-lg">
                    <strong className="text-slate-900 block font-sans">1. Frontend Build Assets:</strong>
                    <code>dist/</code> (generated by <code>npm run build</code>)
                  </div>
                  <div className="p-2.5 bg-slate-50 border border-slate-200 rounded-lg">
                    <strong className="text-slate-900 block font-sans">2. Server Entry &amp; APIs:</strong>
                    <code>server.ts</code>, <code>src/server/api.ts</code>
                  </div>
                  <div className="p-2.5 bg-slate-50 border border-slate-200 rounded-lg">
                    <strong className="text-slate-900 block font-sans">3. Supabase / Cloud DB:</strong>
                    Database connection link configured in Settings
                  </div>
                  <div className="p-2.5 bg-slate-50 border border-slate-200 rounded-lg">
                    <strong className="text-slate-900 block font-sans">4. Build Configuration:</strong>
                    <code>package.json</code>, <code>vite.config.ts</code>
                  </div>
                </div>
              </div>

              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-1">Cloudflare Pages Build Settings:</h4>
                <div className="bg-slate-900 text-slate-200 p-3.5 rounded-xl font-mono text-[11px] space-y-1 relative">
                  <div># Build Command:</div>
                  <div className="text-emerald-400 font-bold">npm run build</div>
                  <div className="pt-2"># Build Output Directory:</div>
                  <div className="text-amber-300 font-bold">dist</div>
                </div>
              </div>
            </div>
          )}

          {activePlatform === 'github' && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-slate-100 border border-slate-300 text-slate-900 leading-relaxed">
                <strong>Publishing to GitHub:</strong> Upload your codebase to a GitHub repository to version control all academy records, manage automated CI/CD workflows, and collaborate with your team.
              </div>

              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Step-by-Step Git Commands:</h4>
                <div className="bg-slate-900 text-slate-200 p-4 rounded-xl font-mono text-[11px] space-y-2 relative group">
                  <button
                    onClick={() =>
                      copyToClipboard(
                        'git init\ngit add .\ngit commit -m "Initial commit of Nexus Academy"\ngit branch -M main\ngit remote add origin https://github.com/Sohail1q/nexus-academy.git\ngit push -u origin main',
                        'git'
                      )
                    }
                    className="absolute right-3 top-3 px-2 py-1 bg-slate-800 hover:bg-slate-700 text-white rounded text-[10px] flex items-center gap-1 cursor-pointer"
                  >
                    {copiedCmd === 'git' ? <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                    {copiedCmd === 'git' ? 'Copied!' : 'Copy Commands'}
                  </button>
                  <p className="text-slate-400"># 1. Initialize git and stage all files</p>
                  <p className="text-emerald-400">git init</p>
                  <p className="text-emerald-400">git add .</p>
                  <p className="text-emerald-400">git commit -m "Initial commit of Nexus Academy"</p>
                  <p className="text-slate-400"># 2. Link your remote repository and push</p>
                  <p className="text-emerald-400">git branch -M main</p>
                  <p className="text-emerald-400">git remote add origin https://github.com/Sohail1q/nexus-academy.git</p>
                  <p className="text-emerald-400">git push -u origin main</p>
                </div>
              </div>
            </div>
          )}

          {activePlatform === 'cloudrun' && (
            <div className="space-y-4">
              <div className="p-4 rounded-xl bg-blue-50/70 border border-blue-200 text-blue-900 leading-relaxed">
                <strong>Google Cloud Run &amp; Port 3000 Server:</strong> The current workspace executes a real-time Express server listening exclusively on Port 3000 with Server-Sent Events (SSE) for instant cross-device synchronization.
              </div>

              <div>
                <h4 className="font-bold text-slate-900 text-sm mb-2">Production Start Command:</h4>
                <div className="bg-slate-900 text-slate-200 p-3.5 rounded-xl font-mono text-[11px]">
                  <div className="text-slate-400"># Start production daemon on port 3000:</div>
                  <div className="text-emerald-400 font-bold">node server.ts</div>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-slate-200 bg-slate-50 flex items-center justify-end gap-3">
          <button
            onClick={onClose}
            className="h-10 px-5 rounded-lg bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold transition cursor-pointer"
          >
            Close Guide
          </button>
        </div>
      </div>
    </div>
  );
};
